name: Build and Deploy to Google Cloud

on:
  push:
    branches: [ main ]  # Trigger the workflow on push to main branch

env:
  REGISTRY: ${{ secrets.GCP_REGISTRY }}
  REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: munchi-merchant-api
  SERVICE_NAME: munchi-merchant-dev-api  # If this is different from the image name
  REGION: europe-north1  # Assuming this is your region, adjust if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ env.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ env.REGISTRY }}

    - name: Set execute permissions for scripts
      run: |
        chmod +x scripts/build_gcloud_image.sh
        chmod +x scripts/push_gcloud_image.sh

    - name: Build Docker image
      run: ./scripts/build_gcloud_image.sh

    - name: Push Docker image
      run: ./scripts/push_gcloud_image.sh

    - name: Deploy new revision to Cloud Run
      run: |
        FULL_IMAGE_NAME="${REGISTRY}/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:latest"
        echo "Deploying image: $FULL_IMAGE_NAME"
        gcloud run deploy "${SERVICE_NAME}" \
          --image "${FULL_IMAGE_NAME}" \
          --platform managed \
          --region "${REGION}" \
          --project "${PROJECT_ID}"

    - name: Print completion message
      run: echo "Build and push completed for ${{ env.IMAGE_NAME }}"